version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fircle
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/fircle
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
